version: '3.8'

services:
  api-server:
    build:
      context: ./repo
      dockerfile: apps/api-server/Dockerfile
    container_name: api-server
    restart: unless-stopped
    ports:
      - "9001:9001"
    env_file: ./repo/.env
    environment:
      NODE_ENV: production
      PORT: 9001
      KAFKA_BROKER: kafka:9092
      CLICKHOUSE_URL: http://clickhouse:8123
    networks:
      - infra

  s3-reverse-proxy:
    build:
      context: ./repo
      dockerfile: apps/s3-reverse-proxy-server/Dockerfile
    container_name: s3-reverse-proxy
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: ./repo/.env
    environment:
      NODE_ENV: production
      PORT: 8000
    networks:
      - infra

  zero:
    build:
      context: ./repo
      dockerfile: apps/zero/Dockerfile
    container_name: zero
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: ./repo/.env
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_SERVER_URL: http://13.233.192.101:9001
    networks:
      - infra

networks:
  infra:
    external: true
    name: app_default